Repository WEB-We-arE-Best/Delivery-System, pull requests merged in 2024-10, with the labels that each got.

#17 라이더 CRUD 기능 추가
  core/app-core/build.gradle
  service/rider/build.gradle
  service/rider/src/main/java/com/webest/rider/application/RiderService.java
  service/rider/src/main/java/com/webest/rider/application/RiderServiceImpl.java
  service/rider/src/main/java/com/webest/rider/common/exception/RiderErrorCode.java
  service/rider/src/main/java/com/webest/rider/common/exception/RiderException.java
  service/rider/src/main/java/com/webest/rider/common/security/WebSecurityConfig.java
  service/rider/src/main/java/com/webest/rider/domain/model/Rider.java
  service/rider/src/main/java/com/webest/rider/domain/model/RiderSearchCondition.java
  service/rider/src/main/java/com/webest/rider/domain/model/RiderTransportation.java
  service/rider/src/main/java/com/webest/rider/domain/model/converter/RiderAddressConverter.java
  service/rider/src/main/java/com/webest/rider/domain/model/vo/PhoneNumber.java
  service/rider/src/main/java/com/webest/rider/domain/repository/RiderQueryRepository.java
  service/rider/src/main/java/com/webest/rider/domain/repository/RiderRepository.java
  service/rider/src/main/java/com/webest/rider/infrastructure/RiderJpaRepository.java
  service/rider/src/main/java/com/webest/rider/infrastructure/RiderQueryRepositoryImpl.java
  service/rider/src/main/java/com/webest/rider/infrastructure/querydsl/QueryDslConfig.java
  service/rider/src/main/java/com/webest/rider/presentation/RiderController.java
  service/rider/src/main/java/com/webest/rider/presentation/RiderEndPoint.java
  service/rider/src/main/java/com/webest/rider/presentation/dtos/request/RiderCreateRequestDto.java
  service/rider/src/main/java/com/webest/rider/presentation/dtos/request/RiderLoginRequestDto.java
  service/rider/src/main/java/com/webest/rider/presentation/dtos/request/RiderRegisterAddressRequestDto.java
  service/rider/src/main/java/com/webest/rider/presentation/dtos/request/RiderUpdateRequestDto.java
  service/rider/src/main/java/com/webest/rider/presentation/dtos/response/RiderResponseDto.java
  service/rider/src/main/resources/application.yml
  service/rider/src/test/resources/application.yml
Labels: enhancement

#18 feat: 가게 생성, 가게 주소 등록 구현
  service/store/src/main/java/com/webest/store/StoreApplication.java
  service/store/src/main/java/com/webest/store/category/api/CategoryController.java
  service/store/src/main/java/com/webest/store/category/domain/StoreCategory.java
  service/store/src/main/java/com/webest/store/store/api/StoreController.java
  service/store/src/main/java/com/webest/store/store/api/dto/CreateStoreRequest.java
  service/store/src/main/java/com/webest/store/store/api/dto/StoreResponse.java
  service/store/src/main/java/com/webest/store/store/api/dto/UpdateStoreAddressRequest.java
  service/store/src/main/java/com/webest/store/store/application/StoreService.java
  service/store/src/main/java/com/webest/store/store/domain/Store.java
  service/store/src/main/java/com/webest/store/store/domain/StoreRepository.java
  service/store/src/main/java/com/webest/store/store/domain/StoreStatus.java
  service/store/src/main/java/com/webest/store/store/exception/StoreErrorCode.java
  service/store/src/main/java/com/webest/store/store/exception/StoreException.java
  service/store/src/main/java/com/webest/store/store/infra/naver/NaverGeoClient.java
  service/store/src/main/java/com/webest/store/store/infra/naver/NaverGeoClientHeaderConfig.java
  service/store/src/main/java/com/webest/store/store/infra/naver/NaverRequestInterceptor.java
  service/store/src/main/java/com/webest/store/store/infra/naver/dto/AddressElement.java
  service/store/src/main/java/com/webest/store/store/infra/naver/dto/GeoResponse.java
  service/store/src/main/java/com/webest/store/store/infra/naver/dto/Meta.java
  service/store/src/main/java/com/webest/store/store/infra/naver/dto/NaverAddress.java
  service/store/src/main/resources/application.yml
Labels: enhancement

#23 feat: 유저 쿠폰 관련 기능 추가 - close #22
  service/coupon/src/main/java/com/webest/coupon/application/CouponServiceImpl.java
  service/coupon/src/main/java/com/webest/coupon/application/CouponUserService.java
  service/coupon/src/main/java/com/webest/coupon/application/CouponUserServiceImpl.java
  service/coupon/src/main/java/com/webest/coupon/common/exception/CouponErrorCode.java
  service/coupon/src/main/java/com/webest/coupon/domain/dtos/CouponByUserDto.java
  service/coupon/src/main/java/com/webest/coupon/domain/dtos/CouponCheckData.java
  service/coupon/src/main/java/com/webest/coupon/domain/model/Coupon.java
  service/coupon/src/main/java/com/webest/coupon/domain/model/CouponUser.java
  service/coupon/src/main/java/com/webest/coupon/domain/repository/CouponQueryRepository.java
  service/coupon/src/main/java/com/webest/coupon/domain/repository/CouponRepository.java
  service/coupon/src/main/java/com/webest/coupon/domain/service/CouponDomainServiceImpl.java
  service/coupon/src/main/java/com/webest/coupon/infrastructure/CouponJpaRepository.java
  service/coupon/src/main/java/com/webest/coupon/infrastructure/CouponQueryRepositoryImpl.java
  service/coupon/src/main/java/com/webest/coupon/mapper/CouponMapper.java
  service/coupon/src/main/java/com/webest/coupon/presentation/CouponUserController.java
  service/coupon/src/main/java/com/webest/coupon/presentation/dtos/request/CouponCreateRequestDto.java
  service/coupon/src/main/java/com/webest/coupon/presentation/dtos/request/CouponUpdateRequestDto.java
  service/coupon/src/main/java/com/webest/coupon/presentation/dtos/request/CouponUsedRequestDto.java
  service/coupon/src/main/java/com/webest/coupon/presentation/dtos/response/CouponByUserResponseDto.java
  service/coupon/src/main/java/com/webest/coupon/presentation/dtos/response/CouponResponseDto.java
  service/coupon/src/test/resources/application.yml
Labels: enhancement

#26 fix: 다른 운영체제에서 빌드가 안되는 문제 해결
  .DS_Store
  .gitignore
  gradle/.DS_Store
  gradle/wrapper/.DS_Store
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  infra/eureka/gradle/wrapper/gradle-wrapper.jar
  infra/eureka/gradle/wrapper/gradle-wrapper.properties
  infra/gateway/gradle/wrapper/gradle-wrapper.jar
  infra/gateway/gradle/wrapper/gradle-wrapper.properties
  service/auth/gradle/wrapper/gradle-wrapper.jar
  service/auth/gradle/wrapper/gradle-wrapper.properties
  service/coupon/gradle/wrapper/gradle-wrapper.jar
  service/coupon/gradle/wrapper/gradle-wrapper.properties
  service/delivery/gradle/wrapper/gradle-wrapper.jar
  service/delivery/gradle/wrapper/gradle-wrapper.properties
  service/order/gradle/wrapper/gradle-wrapper.jar
  service/order/gradle/wrapper/gradle-wrapper.properties
  service/payment/gradle/wrapper/gradle-wrapper.jar
  service/payment/gradle/wrapper/gradle-wrapper.properties
  service/rider/gradle/wrapper/gradle-wrapper.jar
  service/rider/gradle/wrapper/gradle-wrapper.properties
  service/store/gradle/wrapper/gradle-wrapper.jar
  service/store/gradle/wrapper/gradle-wrapper.properties
  service/user/gradle/wrapper/gradle-wrapper.jar
  service/user/gradle/wrapper/gradle-wrapper.properties
  settings.gradle
Labels: bug

#28 feat/add-product-crud
  service/store/src/main/java/com/webest/store/product/application/ProductService.java
  service/store/src/main/java/com/webest/store/product/domain/Product.java
  service/store/src/main/java/com/webest/store/product/domain/ProductRepository.java
  service/store/src/main/java/com/webest/store/product/domain/ProductStatus.java
  service/store/src/main/java/com/webest/store/product/exception/ProductErrorCode.java
  service/store/src/main/java/com/webest/store/product/exception/ProductException.java
  service/store/src/main/java/com/webest/store/product/presentation/ProductController.java
  service/store/src/main/java/com/webest/store/product/presentation/dto/CreateProductRequest.java
  service/store/src/main/java/com/webest/store/product/presentation/dto/ProductResponse.java
  service/store/src/main/java/com/webest/store/product/presentation/dto/UpdateProductDetailsRequest.java
  service/store/src/main/java/com/webest/store/product/presentation/dto/UpdateProductStatusRequest.java
  service/store/src/main/java/com/webest/store/store/application/StoreService.java
  service/store/src/main/java/com/webest/store/store/domain/Store.java
  service/store/src/main/java/com/webest/store/store/presentation/StoreController.java
  service/store/src/main/java/com/webest/store/store/presentation/dto/CreateStoreRequest.java
  service/store/src/main/java/com/webest/store/store/presentation/dto/StoreResponse.java
  service/store/src/main/java/com/webest/store/store/presentation/dto/UpdateStoreAddressRequest.java
Labels: enhancement

#36 feat: 쿠폰 갯수 Lock을 활용한 동시성 처리 - close #24
  .gitignore
  core/app-core/src/main/java/com/webest/app/jpa/JpaAuditConfig.java
  service/coupon/.gitignore
  service/coupon/build.gradle
  service/coupon/src/main/java/com/webest/coupon/application/CouponUserServiceImpl.java
  service/coupon/src/main/java/com/webest/coupon/common/aop/RedissonLock.java
  service/coupon/src/main/java/com/webest/coupon/common/aop/RedissonLockAspect.java
  service/coupon/src/main/java/com/webest/coupon/common/exception/CouponErrorCode.java
  service/coupon/src/main/java/com/webest/coupon/common/parser/CustomSpringELParser.java
  service/coupon/src/main/java/com/webest/coupon/common/property/RedisProperty.java
  service/coupon/src/main/java/com/webest/coupon/infrastructure/CouponJpaRepository.java
  service/coupon/src/main/java/com/webest/coupon/infrastructure/config/PropertyConfig.java
  service/coupon/src/main/java/com/webest/coupon/infrastructure/config/RedisConfig.java
  service/coupon/src/main/java/com/webest/coupon/infrastructure/config/RedissonConfig.java
  service/coupon/src/main/java/com/webest/coupon/presentation/dtos/response/CouponResponseDto.java
  service/coupon/src/main/resources/application.yml
  service/coupon/src/test/java/com/webest/coupon/application/CouponUserServiceImplTest.java
  service/coupon/src/test/java/com/webest/coupon/application/config/TestContainerConfig.java
  service/coupon/src/test/resources/application.yml
Labels: enhancement

#37 feat: 상점 배달 가능 지역(법정동), 법정동으로 상점 검색, 캐싱 구현
  service/store/build.gradle
  service/store/src/main/java/com/webest/store/product/application/ProductService.java
  service/store/src/main/java/com/webest/store/product/domain/Product.java
  service/store/src/main/java/com/webest/store/store/application/AddressServiceImpl.java
  service/store/src/main/java/com/webest/store/store/application/StoreService.java
  service/store/src/main/java/com/webest/store/store/domain/model/Store.java
  service/store/src/main/java/com/webest/store/store/domain/model/StoreStatus.java
  service/store/src/main/java/com/webest/store/store/domain/repository/CustomStoreRepository.java
  service/store/src/main/java/com/webest/store/store/domain/repository/StoreRepository.java
  service/store/src/main/java/com/webest/store/store/infrastructure/naver/NaverGeoClient.java
  service/store/src/main/java/com/webest/store/store/infrastructure/naver/NaverGeoClientHeaderConfig.java
  service/store/src/main/java/com/webest/store/store/infrastructure/naver/NaverRequestInterceptor.java
  service/store/src/main/java/com/webest/store/store/infrastructure/naver/dto/AddressElement.java
  service/store/src/main/java/com/webest/store/store/infrastructure/naver/dto/GeoResponse.java
  service/store/src/main/java/com/webest/store/store/infrastructure/naver/dto/Meta.java
  service/store/src/main/java/com/webest/store/store/infrastructure/naver/dto/NaverAddress.java
  service/store/src/main/java/com/webest/store/store/infrastructure/querydsl/CustomStoreRepositoryImpl.java
  service/store/src/main/java/com/webest/store/store/infrastructure/querydsl/QueryDslConfig.java
  service/store/src/main/java/com/webest/store/store/infrastructure/redis/CacheConfig.java
  service/store/src/main/java/com/webest/store/store/infrastructure/redis/RedisCacheConfig.java
  service/store/src/main/java/com/webest/store/store/presentation/StoreController.java
  service/store/src/main/java/com/webest/store/store/presentation/dto/CreateStoreRequest.java
  service/store/src/main/java/com/webest/store/store/presentation/dto/DeliveryAreaRequest.java
  service/store/src/main/java/com/webest/store/store/presentation/dto/StoreResponse.java
  service/store/src/main/resources/application.yml
Labels: enhancement

#40 feat: 쿠폰 트래픽 제어를 위한 카프카 및 레디스 기능 추가 - close #39
  core/app-core/src/main/java/com/webest/app/address/csv/ReadAddressCsv.java
  service/coupon/build.gradle
  service/coupon/src/main/java/com/webest/coupon/application/CouponUserService.java
  service/coupon/src/main/java/com/webest/coupon/application/CouponUserServiceImpl.java
  service/coupon/src/main/java/com/webest/coupon/common/exception/CouponErrorCode.java
  service/coupon/src/main/java/com/webest/coupon/common/exception/KafkaErrorHandler.java
  service/coupon/src/main/java/com/webest/coupon/common/parser/KafkaEventSerializer.java
  service/coupon/src/main/java/com/webest/coupon/common/value/CouponRedisStatus.java
  service/coupon/src/main/java/com/webest/coupon/common/value/CouponStaticValue.java
  service/coupon/src/main/java/com/webest/coupon/domain/model/Coupon.java
  service/coupon/src/main/java/com/webest/coupon/domain/service/CouponDomainService.java
  service/coupon/src/main/java/com/webest/coupon/domain/service/CouponDomainServiceImpl.java
  service/coupon/src/main/java/com/webest/coupon/domain/service/CouponRedisService.java
  service/coupon/src/main/java/com/webest/coupon/domain/service/CouponRedisServiceImpl.java
  service/coupon/src/main/java/com/webest/coupon/infrastructure/config/KafkaConfig.java
  service/coupon/src/main/java/com/webest/coupon/infrastructure/config/RedisConfig.java
  service/coupon/src/main/java/com/webest/coupon/infrastructure/kafka/KafkaProducerListener.java
  service/coupon/src/main/java/com/webest/coupon/presentation/CouponKafkaEndpoint.java
  service/coupon/src/main/java/com/webest/coupon/presentation/CouponUserController.java
  service/coupon/src/main/java/com/webest/coupon/presentation/dtos/request/CouponKafkaIssueDto.java
  service/coupon/src/main/java/com/webest/coupon/presentation/dtos/response/CouponIssueResponseDto.java
  service/coupon/src/main/java/com/webest/coupon/presentation/dtos/response/CouponOffsetResponseDto.java
  service/coupon/src/main/resources/application.yml
Labels: enhancement

#44 refactor : store 주소 embedded로 변경, 가게 주소 등록시 법정동 코드도 등록되게 수정
  service/store/src/main/java/com/webest/store/store/application/StoreService.java
  service/store/src/main/java/com/webest/store/store/domain/model/Store.java
  service/store/src/main/java/com/webest/store/store/domain/model/StoreAddress.java
  service/store/src/main/java/com/webest/store/store/presentation/StoreController.java
  service/store/src/main/java/com/webest/store/store/presentation/dto/StoreResponse.java
  service/store/src/main/java/com/webest/store/store/presentation/dto/UpdateStoreAddressRequest.java
Labels: enhancement

#46 feat: 반경 내 가게 조회 기능
  infra/gateway/src/main/resources/application.yml
  service/store/src/main/java/com/webest/store/store/application/GeoOperation.java
  service/store/src/main/java/com/webest/store/store/application/StoreCacheService.java
  service/store/src/main/java/com/webest/store/store/application/StoreService.java
  service/store/src/main/java/com/webest/store/store/infrastructure/redis/RedisCacheConfig.java
  service/store/src/main/java/com/webest/store/store/infrastructure/user/UserClient.java
  service/store/src/main/java/com/webest/store/store/infrastructure/user/dto/UserResponse.java
  service/store/src/main/java/com/webest/store/store/presentation/StoreController.java
  service/store/src/main/java/com/webest/store/store/presentation/dto/Coordinates.java
Labels: enhancement

#49 feat: 배달 가게 전체 조회 User role별로 분기
  service/store/src/main/java/com/webest/store/store/application/StoreService.java
  service/store/src/main/java/com/webest/store/store/application/context/StoreStrategyContext.java
  service/store/src/main/java/com/webest/store/store/domain/strategy/MasterStoreStrategy.java
  service/store/src/main/java/com/webest/store/store/domain/strategy/StoreStrategy.java
  service/store/src/main/java/com/webest/store/store/domain/strategy/UserStoreStrategy.java
  service/store/src/main/java/com/webest/store/store/exception/StoreErrorCode.java
  service/store/src/main/java/com/webest/store/store/presentation/StoreController.java
Labels: enhancement

#53 ci: ci파일 추가 - close #50
  .env.example
  .github/workflows/auth-ci.yml
  .github/workflows/coupon-ci.yml
  .github/workflows/delivery-ci.yml
  .github/workflows/eureka-ci.yml
  .github/workflows/gateway-ci.yml
  .github/workflows/order-ci.yml
  .github/workflows/rider-ci.yml
  .github/workflows/store-ci.yml
  .github/workflows/user-ci.yml
  .gitignore
  build_service.sh
  docker-compose.yml
  push_to_ecr.sh
Labels: enhancement

#54 feat: store 유저 권한별 처리
  infra/gateway/src/main/java/com/webest/gateway/config/FilterConfig.java
  service/store/src/main/java/com/webest/store/store/application/StoreService.java
  service/store/src/main/java/com/webest/store/store/domain/model/Store.java
  service/store/src/main/java/com/webest/store/store/presentation/StoreController.java
  service/store/src/main/java/com/webest/store/store/presentation/dto/CreateStoreRequest.java
  service/store/src/main/java/com/webest/store/store/presentation/dto/StoreResponse.java
Labels: enhancement

#59 feat: user를 Long에서 String으로 변경
  core/app-core/src/main/java/com/webest/app/jpa/BaseEntity.java
  core/app-core/src/main/java/com/webest/app/jpa/JpaAuditConfig.java
  core/web-core/src/main/java/com/webest/web/common/CommonStaticVariable.java
  docker-compose.yml
  infra/eureka/src/main/resources/application-dev.yml
  infra/gateway/.env.example
  infra/gateway/src/main/resources/application-dev.yml
  service/auth/src/main/resources/application-dev.yml
  service/coupon/src/main/java/com/webest/coupon/CouponApplication.java
  service/coupon/src/main/java/com/webest/coupon/application/CouponUserService.java
  service/coupon/src/main/java/com/webest/coupon/application/CouponUserServiceImpl.java
  service/coupon/src/main/java/com/webest/coupon/application/client/UserClient.java
  service/coupon/src/main/java/com/webest/coupon/application/client/dtos/UserResponse.java
  service/coupon/src/main/java/com/webest/coupon/common/exception/CouponErrorCode.java
  service/coupon/src/main/java/com/webest/coupon/common/exception/CustomFeignErrorDecoder.java
  service/coupon/src/main/java/com/webest/coupon/domain/model/CouponUser.java
  service/coupon/src/main/java/com/webest/coupon/domain/repository/CouponQueryRepository.java
  service/coupon/src/main/java/com/webest/coupon/domain/service/CouponRedisService.java
  service/coupon/src/main/java/com/webest/coupon/domain/service/CouponRedisServiceImpl.java
  service/coupon/src/main/java/com/webest/coupon/infrastructure/CouponJpaRepository.java
  service/coupon/src/main/java/com/webest/coupon/infrastructure/CouponQueryRepositoryImpl.java
  service/coupon/src/main/java/com/webest/coupon/infrastructure/config/FeignClientConfig.java
  service/coupon/src/main/java/com/webest/coupon/presentation/CouponController.java
  service/coupon/src/main/java/com/webest/coupon/presentation/CouponUserController.java
  service/coupon/src/main/java/com/webest/coupon/presentation/dtos/request/CouponKafkaIssueDto.java
  service/coupon/src/main/java/com/webest/coupon/presentation/dtos/request/CouponUsedRequestDto.java
  service/coupon/src/main/java/com/webest/coupon/presentation/dtos/response/CouponOffsetResponseDto.java
  service/coupon/src/main/resources/application-dev.yml
  service/coupon/src/test/java/com/webest/coupon/application/CouponUserServiceImplTest.java
  service/coupon/src/test/resources/application.yml
  service/delivery/src/main/resources/application-dev.yml
  service/order/src/main/resources/application-dev.yml
  service/rider/src/main/java/com/webest/rider/presentation/filter/AccessFilter.java
  service/rider/src/main/resources/application-dev.yml
  service/store/src/main/resources/application-dev.yml
  service/user/src/main/resources/application-dev.yml
Labels: enhancement

#71 docs: 기본 Swagger 구성 설정
  core/web-core/build.gradle
  core/web-core/src/main/java/com/webest/web/common/CommonStaticVariable.java
  infra/gateway/build.gradle
  infra/gateway/src/main/java/com/webest/gateway/config/FilterConfig.java
  infra/gateway/src/main/java/com/webest/gateway/filter/AuthorizationHeaderFilter.java
  infra/gateway/src/main/resources/application-dev.yml
  infra/gateway/src/main/resources/application.yml
  service/auth/src/main/java/com/webest/auth/infrastructure/config/SwaggerConfig.java
  service/auth/src/main/java/com/webest/auth/infrastructure/config/WebSecurityConfig.java
  service/auth/src/main/resources/application-dev.yml
  service/auth/src/main/resources/application.yml
  service/coupon/src/main/java/com/webest/coupon/infrastructure/config/SwaggerConfig.java
  service/coupon/src/main/resources/application-dev.yml
  service/coupon/src/main/resources/application.yml
  service/delivery/src/main/java/com/webest/delivery/infrastructure/configuration/SwaggerConfig.java
  service/delivery/src/main/resources/application-dev.yml
  service/delivery/src/main/resources/application.yml
  service/order/src/main/java/com/webest/order/infrastructure/configuration/SwaggerConfig.java
  service/order/src/main/resources/application-dev.yml
  service/order/src/main/resources/application.yml
  service/rider/src/main/java/com/webest/rider/infrastructure/config/SwaggerConfig.java
  service/rider/src/main/resources/application-dev.yml
  service/rider/src/main/resources/application.yml
  service/store/src/main/java/com/webest/store/common/config/SwaggerConfig.java
  service/store/src/main/resources/application-dev.yml
  service/store/src/main/resources/application.yml
  service/user/src/main/java/com/webest/user/config/SwaggerConfig.java
  service/user/src/main/resources/application-dev.yml
  service/user/src/main/resources/application-local.yml
Labels: documentation

#79 feat: validation을 위한 custom annotation 및 적용 -close #78
  core/web-core/src/main/java/com/webest/web/exception/GlobalExceptionHandler.java
  core/web-core/src/main/java/com/webest/web/validator/EnumValidation.java
  core/web-core/src/main/java/com/webest/web/validator/EnumValidator.java
  service/coupon/src/main/java/com/webest/coupon/application/CouponUserServiceImpl.java
  service/coupon/src/main/java/com/webest/coupon/common/exception/CouponErrorCode.java
  service/coupon/src/main/java/com/webest/coupon/common/exception/CustomFeignErrorDecoder.java
  service/coupon/src/main/java/com/webest/coupon/common/interceptor/FeignClientInterceptor.java
  service/coupon/src/main/java/com/webest/coupon/domain/model/DateType.java
  service/coupon/src/main/java/com/webest/coupon/infrastructure/config/FeignClientConfig.java
  service/coupon/src/main/java/com/webest/coupon/presentation/CouponController.java
  service/coupon/src/main/java/com/webest/coupon/presentation/CouponUserController.java
  service/coupon/src/main/java/com/webest/coupon/presentation/dtos/request/CouponCreateRequestDto.java
  service/coupon/src/main/java/com/webest/coupon/presentation/dtos/request/CouponUpdateRequestDto.java
  service/coupon/src/test/java/com/webest/coupon/application/CouponUserServiceImplTest.java
Labels: enhancement

#81 feat: auth모듈에서 라이더 로그인 추가
  core/web-core/src/main/java/com/webest/web/exception/GlobalExceptionHandler.java
  service/auth/src/main/java/com/webest/auth/application/AuthService.java
  service/auth/src/main/java/com/webest/auth/application/AuthServiceImpl.java
  service/auth/src/main/java/com/webest/auth/application/JwtTokenService.java
  service/auth/src/main/java/com/webest/auth/application/RiderAuthService.java
  service/auth/src/main/java/com/webest/auth/common/exception/AuthErrorCode.java
  service/auth/src/main/java/com/webest/auth/infrastructure/config/AuthenticationFilter.java
  service/auth/src/main/java/com/webest/auth/infrastructure/core/RiderClient.java
  service/auth/src/main/java/com/webest/auth/infrastructure/core/dto/RiderResponseDto.java
  service/auth/src/main/java/com/webest/auth/presentation/controller/AuthController.java
  service/auth/src/main/java/com/webest/auth/presentation/dto/request/rider/RiderAuthRequestDto.java
  service/auth/src/main/java/com/webest/auth/presentation/dto/request/rider/RiderCreateRequestDto.java
  service/rider/src/main/java/com/webest/rider/application/RiderService.java
  service/rider/src/main/java/com/webest/rider/application/RiderServiceImpl.java
  service/rider/src/main/java/com/webest/rider/common/exception/RiderErrorCode.java
  service/rider/src/main/java/com/webest/rider/presentation/RiderController.java
  service/rider/src/main/java/com/webest/rider/presentation/RiderEndPoint.java
  service/rider/src/main/java/com/webest/rider/presentation/dtos/request/RiderCreateRequestDto.java
  service/rider/src/main/java/com/webest/rider/presentation/dtos/request/RiderUpdateRequestDto.java
Labels: enhancement

#82 feat: 포장 가게 조회 기능 & 가게, 상품, 카테고리 validation 처리
  service/store/src/main/java/com/webest/store/category/presentation/CategoryController.java
  service/store/src/main/java/com/webest/store/category/presentation/dto/CreateCategoryRequest.java
  service/store/src/main/java/com/webest/store/category/presentation/dto/UpdateCategoryRequest.java
  service/store/src/main/java/com/webest/store/product/presentation/ProductController.java
  service/store/src/main/java/com/webest/store/product/presentation/dto/CreateProductRequest.java
  service/store/src/main/java/com/webest/store/product/presentation/dto/UpdateProductDetailsRequest.java
  service/store/src/main/java/com/webest/store/product/presentation/dto/UpdateProductStatusRequest.java
  service/store/src/main/java/com/webest/store/store/application/context/StoreStrategyContext.java
  service/store/src/main/java/com/webest/store/store/domain/strategy/MasterStoreStrategy.java
  service/store/src/main/java/com/webest/store/store/domain/strategy/StoreStrategy.java
  service/store/src/main/java/com/webest/store/store/domain/strategy/UserStoreStrategy.java
  service/store/src/main/java/com/webest/store/store/infrastructure/user/dto/UserResponse.java
  service/store/src/main/java/com/webest/store/store/presentation/StoreController.java
  service/store/src/main/java/com/webest/store/store/presentation/dto/CreateStoreRequest.java
  service/store/src/main/java/com/webest/store/store/presentation/dto/UpdateStoreAddressRequest.java
Labels: enhancement

#84 feat: 라이더의 기본 기능 완성 - close #80
  infra/gateway/src/main/java/com/webest/gateway/config/FilterConfig.java
  service/rider/src/main/java/com/webest/rider/application/feign/DeliveryClient.java
  service/rider/src/main/java/com/webest/rider/application/feign/dtos/DeliveryResponse.java
  service/rider/src/main/java/com/webest/rider/application/feign/dtos/DeliverySearchRequest.java
  service/rider/src/main/java/com/webest/rider/common/constant/DeliveryStatus.java
  service/rider/src/main/java/com/webest/rider/common/constant/StaticVariable.java
  service/rider/src/main/java/com/webest/rider/common/exception/RiderErrorCode.java
  service/rider/src/main/java/com/webest/rider/infrastructure/config/SwaggerConfig.java
  service/rider/src/main/java/com/webest/rider/infrastructure/config/WebMvcConfig.java
  service/rider/src/main/java/com/webest/rider/presentation/RiderController.java
  service/rider/src/main/java/com/webest/rider/presentation/interceptor/RiderInterceptor.java
Labels: enhancement

#87 Feat: 라이더와 쿠폰에 LogStash 연결 위한 기능 추가 - close #86
  .env.example
  core/web-core/src/main/java/com/webest/web/exception/GlobalExceptionHandler.java
  docker-compose.yml
  service/coupon/build.gradle
  service/coupon/src/main/java/com/webest/coupon/common/value/CouponStaticValue.java
  service/coupon/src/main/java/com/webest/coupon/infrastructure/config/WebMvcConfig.java
  service/coupon/src/main/java/com/webest/coupon/presentation/filter/MDCLoggingFilter.java
  service/coupon/src/main/resources/application-dev.yml
  service/coupon/src/main/resources/application.yml
  service/coupon/src/main/resources/logback-spring.xml
  service/rider/build.gradle
  service/rider/src/main/java/com/webest/rider/common/constant/RiderStaticVariable.java
  service/rider/src/main/java/com/webest/rider/common/constant/StaticVariable.java
  service/rider/src/main/java/com/webest/rider/infrastructure/config/SwaggerConfig.java
  service/rider/src/main/java/com/webest/rider/infrastructure/config/WebMvcConfig.java
  service/rider/src/main/java/com/webest/rider/presentation/RiderController.java
  service/rider/src/main/java/com/webest/rider/presentation/filter/AccessFilter.java
  service/rider/src/main/java/com/webest/rider/presentation/filter/MDCLoggingFilter.java
  service/rider/src/main/resources/application-dev.yml
  service/rider/src/main/resources/application.yml
  service/rider/src/main/resources/logback-spring.xml
Labels: enhancement

#90 feat: userCoupon id로 단일 조회
  service/coupon/src/main/java/com/webest/coupon/application/CouponUserService.java
  service/coupon/src/main/java/com/webest/coupon/application/CouponUserServiceImpl.java
  service/coupon/src/main/java/com/webest/coupon/presentation/CouponUserController.java
  service/coupon/src/main/java/com/webest/coupon/presentation/dtos/response/CouponUserResponseDto.java
  service/rider/src/main/resources/application.yml
Labels: enhancement

#91 feat: gateway에서 에러 발생 시 front에 에러 메시지 출력
  infra/gateway/src/main/java/com/webest/gateway/filter/AuthorizationHeaderFilter.java
Labels: enhancement

#92 feat: 배달 상점 검색 기능
  service/store/src/main/java/com/webest/store/store/application/context/StoreStrategyContext.java
  service/store/src/main/java/com/webest/store/store/domain/repository/CustomStoreRepository.java
  service/store/src/main/java/com/webest/store/store/domain/repository/StoreRepository.java
  service/store/src/main/java/com/webest/store/store/domain/strategy/MasterStoreStrategy.java
  service/store/src/main/java/com/webest/store/store/domain/strategy/StoreStrategy.java
  service/store/src/main/java/com/webest/store/store/domain/strategy/UserStoreStrategy.java
  service/store/src/main/java/com/webest/store/store/infrastructure/querydsl/CustomStoreRepositoryImpl.java
  service/store/src/main/java/com/webest/store/store/presentation/StoreController.java
Labels: enhancement

#93 feat: 트래픽이 몰릴 수 있는 쿠폰 모듈에 그라파나 설정
  service/coupon/build.gradle
  service/coupon/src/main/resources/application-dev.yml
  service/coupon/src/main/resources/application.yml
Labels: enhancement
